# Generated by Django 5.1.7 on 2025-03-14 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('traffic_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('average_travel_time_per_10km', models.IntegerField()),
                ('congestion', models.CharField(max_length=15)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='api.country')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vehicles', models.BigIntegerField()),
                ('car', models.IntegerField()),
                ('motorcycles', models.IntegerField()),
                ('trucks', models.IntegerField()),
                ('buses', models.IntegerField()),
                ('other', models.IntegerField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_types', to='api.country')),
            ],
        ),
    ]
